#ifndef _MPI_TAGS
#define _MPI_TAGS

#define COMMUNICATOR_BUFFER_SIZE (64000)
#define COMMUNICATOR_MAX_UNSIGNEDS (COMMUNICATOR_BUFFER_SIZE / sizeof(unsigned))
#define COMMUNICATOR_OFFSET_COUNT (800)

#define MPI_TAG_MESSAGE_UNIT (666)

#endif //_MPI_TAGS
