SET(ALL_SERVICES ${ALL_SERVICES} DeferredRouteTransportWrapper)
SET(ALL_SERVICES ${ALL_SERVICES} MaceTransport)
SET(ALL_SERVICES ${ALL_SERVICES} ProvisionalTransport)
SET(ALL_SERVICES ${ALL_SERVICES} RouteTransportWrapper)
SET(ALL_SERVICES ${ALL_SERVICES} TcpTransport)
SET(ALL_SERVICES ${ALL_SERVICES} UdpTransport)
SET(TcpTransportService_sv_dep TcpTransport)
SET(MaceTransportService_sv_dep MaceTransport ${autoService_sv_dep})
SET(RouteTransportWrapperService_dep ${ServiceClass_h} ${RouteServiceClass_dep} ${TransportServiceClass_dep})
SET(UdpTransportService_sv_dep UdpTransport)
SET(ProvisionalTransportService_dep ${ServiceClass_h} ${ProvisionalTransportServiceClass_dep} ${BufferedTransportServiceClass_dep})
SET(MaceTransportService_dep ${ServiceClass_h} ${BufferedTransportServiceClass_dep} ${TransportServiceClass_dep})
SET(MaceTransportService_sv_list  auto)
SET(RouteTransportWrapperService_lib Transport)
SET(RouteTransportWrapperService_sv_list  auto)
SET(ProvisionalTransportService_lib Transport)
SET(RouteTransportWrapperService_tgt_dep ServiceClass_dep RouteServiceClass_dep TransportServiceClass_dep)
SET(DeferredRouteTransportWrapperService_lib Transport)
SET(DeferredRouteTransportWrapperService_sv_list  TcpTransport)
SET(DeferredRouteTransportWrapperService_sv_dep DeferredRouteTransportWrapper ${TcpTransportService_sv_dep})
SET(TcpTransportService_lib Transport)
SET(RouteTransportWrapperService_sv_dep RouteTransportWrapper ${autoService_sv_dep})
SET(MaceTransportService_tgt_dep ServiceClass_dep BufferedTransportServiceClass_dep TransportServiceClass_dep)
SET(ProvisionalTransportService_sv_list  auto)
SET(ProvisionalTransportService_sv_dep ProvisionalTransport ${autoService_sv_dep})
SET(MaceTransportService_lib Transport)
SET(DeferredRouteTransportWrapperService_dep ${ServiceClass_h} ${RouteServiceClass_dep} ${TransportServiceClass_dep})
SET(ProvisionalTransportService_tgt_dep ServiceClass_dep ProvisionalTransportServiceClass_dep BufferedTransportServiceClass_dep)
SET(UdpTransportService_lib Transport)
SET(DeferredRouteTransportWrapperService_tgt_dep ServiceClass_dep RouteServiceClass_dep TransportServiceClass_dep)
