SET(ALL_SERVICES ${ALL_SERVICES} ReplayTree)
SET(ALL_SERVICES ${ALL_SERVICES} ReplayTreeTest)
SET(ReplayTreeTestService_dep ${ServiceClass_h} ${OverlayServiceClass_dep})
SET(ReplayTreeTestService_tgt_dep ServiceClass_dep OverlayServiceClass_dep)
SET(ReplayTreeTestService_lib ReplayTree)
SET(ReplayTreeTestService_sv_dep ReplayTreeTest ${autoService_sv_dep})
SET(ReplayTreeService_sv_dep ReplayTree ${autoService_sv_dep})
SET(ReplayTreeService_sv_list  auto)
SET(ReplayTreeService_lib ReplayTree)
SET(ReplayTreeService_tgt_dep ServiceClass_dep TreeServiceClass_dep OverlayServiceClass_dep TransportServiceClass_dep)
SET(ReplayTreeTestService_sv_list  auto)
SET(ReplayTreeService_dep ${ServiceClass_h} ${TreeServiceClass_dep} ${OverlayServiceClass_dep} ${TransportServiceClass_dep})
