/**
chuangw: test case 1 is simply composed of a maceInit() transition with a context defined, nothing else.

Purpose: make sure the runtime execute properly in the minimalist fashion.
Also, make sure no extra redundant code is generated.
*/
service TestCase2Lower;
provides ServComp;
trace=high;
typedefs {
}
services {

}

constants {
}
 
state_variables {
  context A{
  }
}

messages {
}
 
transitions {
  downcall (state == init)maceInit()  {
  }
}
