SET(ALL_SERVICES ${ALL_SERVICES} Bamboo)
SET(ALL_SERVICES ${ALL_SERVICES} DeferredBamboo)
SET(BambooService_sv_dep Bamboo ${autoService_sv_dep} ${autoService_sv_dep})
SET(BambooService_lib Bamboo)
SET(DeferredBambooService_lib Bamboo)
SET(BambooService_tgt_dep ServiceClass_dep OverlayRouterServiceClass_dep OverlayServiceClass_dep RouteServiceClass_dep TransportServiceClass_dep)
SET(BambooService_sv_list  auto auto)
SET(DeferredBambooService_sv_list  Bamboo)
SET(BambooService_dep ${ServiceClass_h} ${OverlayRouterServiceClass_dep} ${OverlayServiceClass_dep} ${RouteServiceClass_dep} ${TransportServiceClass_dep})
SET(DeferredBambooService_tgt_dep ServiceClass_dep OverlayRouterServiceClass_dep OverlayServiceClass_dep OverlayRouterServiceClass_dep)
SET(DeferredBambooService_dep ${ServiceClass_h} ${OverlayRouterServiceClass_dep} ${OverlayServiceClass_dep} ${OverlayRouterServiceClass_dep})
SET(DeferredBambooService_sv_dep DeferredBamboo ${BambooService_sv_dep})
