SET(ALL_SERVICES ${ALL_SERVICES} CacheRecursiveOverlayRoute)
SET(ALL_SERVICES ${ALL_SERVICES} LookupTest)
SET(ALL_SERVICES ${ALL_SERVICES} RecursiveOverlayRoute)
SET(RecursiveOverlayRouteService_tgt_dep ServiceClass_dep TransportServiceClass_dep RouteServiceClass_dep OverlayRouterServiceClass_dep TransportServiceClass_dep)
SET(LookupTestService_lib GenericOverlayRoute)
SET(LookupTestService_sv_dep LookupTest ${autoService_sv_dep} ${autoService_sv_dep})
SET(LookupTestService_sv_list  auto auto)
SET(CacheRecursiveOverlayRouteService_sv_list  auto auto)
SET(RecursiveOverlayRouteService_sv_list  auto auto)
SET(RecursiveOverlayRouteService_dep ${ServiceClass_h} ${TransportServiceClass_dep} ${RouteServiceClass_dep} ${OverlayRouterServiceClass_dep} ${TransportServiceClass_dep})
SET(CacheRecursiveOverlayRouteService_sv_dep CacheRecursiveOverlayRoute ${autoService_sv_dep} ${autoService_sv_dep})
SET(CacheRecursiveOverlayRouteService_lib GenericOverlayRoute)
SET(LookupTestService_dep ${ServiceClass_h} ${NullServiceClass_dep} ${TransportServiceClass_dep} ${TransportServiceClass_dep})
SET(RecursiveOverlayRouteService_lib GenericOverlayRoute)
SET(CacheRecursiveOverlayRouteService_tgt_dep ServiceClass_dep TransportServiceClass_dep RouteServiceClass_dep OverlayRouterServiceClass_dep TransportServiceClass_dep)
SET(LookupTestService_tgt_dep ServiceClass_dep NullServiceClass_dep TransportServiceClass_dep TransportServiceClass_dep)
SET(CacheRecursiveOverlayRouteService_dep ${ServiceClass_h} ${TransportServiceClass_dep} ${RouteServiceClass_dep} ${OverlayRouterServiceClass_dep} ${TransportServiceClass_dep})
SET(RecursiveOverlayRouteService_sv_dep RecursiveOverlayRoute ${autoService_sv_dep} ${autoService_sv_dep})
