SET(ALL_SERVICES ${ALL_SERVICES} Chord)
SET(ALL_SERVICES ${ALL_SERVICES} chord_test)
SET(chord_testService_tgt_dep ServiceClass_dep NullServiceClass_dep OverlayServiceClass_dep)
SET(chord_testService_sv_dep chord_test ${autoService_sv_dep})
SET(chord_testService_dep ${ServiceClass_h} ${NullServiceClass_dep} ${OverlayServiceClass_dep})
SET(chord_testService_sv_list  auto)
SET(ChordService_sv_dep Chord ${autoService_sv_dep})
SET(ChordService_dep ${ServiceClass_h} ${OverlayRouterServiceClass_dep} ${OverlayServiceClass_dep} ${TransportServiceClass_dep})
SET(chord_testService_lib Chord)
SET(ChordService_tgt_dep ServiceClass_dep OverlayRouterServiceClass_dep OverlayServiceClass_dep TransportServiceClass_dep)
SET(ChordService_sv_list  auto)
SET(ChordService_lib Chord)
