SET(ReceiveDataHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ReceiveDataHandler.h)
SET(NetworkErrorHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/NetworkErrorHandler.h)
SET(ConnectionStatusHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ConnectionStatusHandler.h)
SET(OverlayJoinHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/OverlayJoinHandler.h)
SET(TransportServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/TransportServiceClass.h)
SET(ForwardDataHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ForwardDataHandler.h)
SET(TreeStructureHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/TreeStructureHandler.h)
SET(GroupJoinHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/GroupJoinHandler.h)
SET(ReceiveDataHandler_dep ${ReceiveDataHandler_h})
SET(NetworkErrorHandler_dep ${NetworkErrorHandler_h})
SET(ServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/interfaces/ServiceClass.h)
SET(ReceiveRequestHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ReceiveRequestHandler.h)
SET(MulticastServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/MulticastServiceClass.h)
SET(ConsensusHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ConsensusHandler.h)
SET(TreeServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/TreeServiceClass.h)
SET(TreeStructureHandler_dep ${TreeStructureHandler_h})
SET(AggregateDataHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/AggregateDataHandler.h)
SET(OverlayStructureHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/OverlayStructureHandler.h)
SET(BufferedTransportServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/BufferedTransportServiceClass.h)
SET(OverlayJoinHandler_dep ${OverlayJoinHandler_h})
SET(OverlayServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/OverlayServiceClass.h)
SET(ConnectionAcceptanceHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ConnectionAcceptanceHandler.h)
SET(JobManagerDataHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/JobManagerDataHandler.h)
SET(DHTDataHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/DHTDataHandler.h)
SET(DeferredMulticastServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/DeferredMulticastServiceClass.h)
SET(FileFindHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/FileFindHandler.h)
SET(ConnectionStatusHandler_dep ${ConnectionStatusHandler_h})
SET(GroupJoinHandler_dep ${GroupJoinHandler_h})
SET(TransportServiceClass_dep ${TransportServiceClass_h} ${ServiceClass_h} ${ReceiveDataHandler_dep} ${NetworkErrorHandler_dep})
SET(ForwardDataHandler_dep ${ForwardDataHandler_h})
SET(GossipDataHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/GossipDataHandler.h)
SET(ScribeTreeHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ScribeTreeHandler.h)
SET(SimHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/SimHandler.h)
SET(MessageStatusHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/MessageStatusHandler.h)
SET(GroupServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/GroupServiceClass.h)
SET(ConsensusServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ConsensusServiceClass.h)
SET(ConnectionAcceptanceHandler_dep ${ConnectionAcceptanceHandler_h})
SET(TreeMaintenanceServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/TreeMaintenanceServiceClass.h)
SET(HierarchicalMulticastServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/HierarchicalMulticastServiceClass.h)
SET(MulticastServiceClass_dep ${MulticastServiceClass_h} ${ServiceClass_h} ${ReceiveDataHandler_dep} ${ForwardDataHandler_dep})
SET(AggregateDataHandler_dep ${AggregateDataHandler_h})
SET(BandwidthTransportServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/BandwidthTransportServiceClass.h)
SET(FileFindHandler_dep ${FileFindHandler_h})
SET(OverlayServiceClass_dep ${OverlayServiceClass_h} ${ServiceClass_h} ${OverlayJoinHandler_dep})
SET(DeferredHierarchicalMulticastServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/DeferredHierarchicalMulticastServiceClass.h)
SET(TransportCryptoServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/TransportCryptoServiceClass.h)
SET(ConnectionAcceptanceServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ConnectionAcceptanceServiceClass.h)
SET(ScribeTreeServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ScribeTreeServiceClass.h)
SET(RouteServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/RouteServiceClass.h)
SET(ReceiveRequestHandler_dep ${ReceiveRequestHandler_h})
SET(ScribeTreeHandler_dep ${ScribeTreeHandler_h})
SET(DHTDataHandler_dep ${DHTDataHandler_h})
SET(HeartBeatServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/HeartBeatServiceClass.h)
SET(BufferedTransportServiceClass_dep ${BufferedTransportServiceClass_h} ${ServiceClass_h} ${TransportServiceClass_dep} ${ConnectionStatusHandler_dep})
SET(GenericGameOfLifeServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/GenericGameOfLifeServiceClass.h)
SET(MessageStatusHandler_dep ${MessageStatusHandler_h})
SET(ServCompServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ServCompServiceClass.h)
SET(GossipDataHandler_dep ${GossipDataHandler_h})
SET(SimHandler_dep ${SimHandler_h})
SET(SimApplicationServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/SimApplicationServiceClass.h)
SET(TreeServiceClass_dep ${TreeServiceClass_h} ${ServiceClass_h} ${TreeStructureHandler_dep})
SET(OverlayRouterServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/OverlayRouterServiceClass.h)
SET(GossipServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/GossipServiceClass.h)
SET(OverlayStructureHandler_dep ${OverlayStructureHandler_h})
SET(RequestTransportServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/RequestTransportServiceClass.h)
SET(JobManagerDataHandler_dep ${JobManagerDataHandler_h})
SET(DHTServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/DHTServiceClass.h)
SET(DeferredMulticastServiceClass_dep ${DeferredMulticastServiceClass_h} ${ServiceClass_h} ${ReceiveDataHandler_dep} ${ForwardDataHandler_dep})
SET(FileStatusHandler_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/FileStatusHandler.h)
SET(ConsensusHandler_dep ${ConsensusHandler_h})
SET(FileFindServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/FileFindServiceClass.h)
SET(GroupServiceClass_dep ${GroupServiceClass_h} ${ServiceClass_h} ${GroupJoinHandler_dep})
SET(ProvisionalTransportServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/ProvisionalTransportServiceClass.h)
SET(AggregateServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/AggregateServiceClass.h)
SET(FileFindServiceClass_dep ${FileFindServiceClass_h} ${ServiceClass_h} ${FileFindHandler_dep})
SET(GossipServiceClass_dep ${GossipServiceClass_h} ${ServiceClass_h} ${GossipDataHandler_dep})
SET(SimApplicationServiceClass_dep ${SimApplicationServiceClass_h} ${ServiceClass_h} ${SimHandler_dep})
SET(HeartBeatServiceClass_dep ${HeartBeatServiceClass_h} ${ServiceClass_h} ${JobManagerDataHandler_dep})
SET(RequestTransportServiceClass_dep ${RequestTransportServiceClass_h} ${ServiceClass_h} ${ReceiveRequestHandler_dep})
SET(TreeMaintenanceServiceClass_dep ${TreeMaintenanceServiceClass_h} ${ServiceClass_h} ${TreeServiceClass_dep})
SET(BandwidthTransportServiceClass_dep ${BandwidthTransportServiceClass_h} ${ServiceClass_h} ${TransportServiceClass_dep})
SET(RouteServiceClass_dep ${RouteServiceClass_h} ${ServiceClass_h} ${TransportServiceClass_dep} ${ForwardDataHandler_dep})
SET(NullServiceClass_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/interfaces/NullServiceClass.h)
SET(ProvisionalTransportServiceClass_dep ${ProvisionalTransportServiceClass_h} ${ServiceClass_h} ${BufferedTransportServiceClass_dep} ${MessageStatusHandler_dep})
SET(GenericGameOfLifeServiceClass_dep ${GenericGameOfLifeServiceClass_h})
SET(DeferredHierarchicalMulticastServiceClass_dep ${DeferredHierarchicalMulticastServiceClass_h} ${ServiceClass_h} ${DeferredMulticastServiceClass_dep})
SET(AggregateServiceClass_dep ${AggregateServiceClass_h} ${ServiceClass_h} ${AggregateDataHandler_dep})
SET(ConsensusServiceClass_dep ${ConsensusServiceClass_h} ${ServiceClass_h} ${ConsensusHandler_dep})
SET(HierarchicalMulticastServiceClass_dep ${HierarchicalMulticastServiceClass_h} ${ServiceClass_h} ${MulticastServiceClass_dep})
SET(ScribeTreeServiceClass_dep ${ScribeTreeServiceClass_h} ${ServiceClass_h} ${TreeServiceClass_dep} ${GroupServiceClass_dep} ${ScribeTreeHandler_dep})
SET(TransportCryptoServiceClass_dep ${TransportCryptoServiceClass_h})
SET(ServCompServiceClass_dep ${ServCompServiceClass_h})
SET(OverlayRouterServiceClass_dep ${OverlayRouterServiceClass_h} ${ServiceClass_h} ${OverlayServiceClass_dep} ${OverlayStructureHandler_dep})
SET(DHTServiceClass_dep ${DHTServiceClass_h} ${ServiceClass_h} ${DHTDataHandler_dep})
SET(ConnectionAcceptanceServiceClass_dep ${ConnectionAcceptanceServiceClass_h} ${ServiceClass_h} ${ConnectionAcceptanceHandler_dep})
SET(FileStatusHandler_dep ${FileStatusHandler_h})
