SET(ALL_SERVICES ${ALL_SERVICES} DeferredScribeMS)
# DEBUG: we ScribeMS variants ARRAY(0x2719cc8)
SET(ScribeMS_VARIANTS ScribeMS Scribe)
SET(ALL_SERVICES ${ALL_SERVICES} ScribeMS Scribe)
SET(ScribeMSService_sv_dep ScribeMS ${autoService_sv_dep} ${autoService_sv_dep} ${autoService_sv_dep})
SET(ScribeService_sv_list  auto auto auto)
SET(DeferredScribeMSService_dep ${ServiceClass_h} ${TreeServiceClass_dep} ${ScribeTreeServiceClass_dep} ${ScribeTreeServiceClass_dep})
SET(ScribeMSService_tgt_dep ServiceClass_dep TreeServiceClass_dep ScribeTreeServiceClass_dep OverlayRouterServiceClass_dep RouteServiceClass_dep RouteServiceClass_dep)
SET(ScribeService_dep ${ServiceClass_h} ${TreeServiceClass_dep} ${ScribeTreeServiceClass_dep} ${OverlayRouterServiceClass_dep} ${RouteServiceClass_dep} ${RouteServiceClass_dep})
SET(ScribeService_sv_dep Scribe ${autoService_sv_dep} ${autoService_sv_dep} ${autoService_sv_dep})
SET(ScribeMSService_lib ScribeMS)
SET(DeferredScribeMSService_tgt_dep ServiceClass_dep TreeServiceClass_dep ScribeTreeServiceClass_dep ScribeTreeServiceClass_dep)
SET(ScribeService_tgt_dep ServiceClass_dep TreeServiceClass_dep ScribeTreeServiceClass_dep OverlayRouterServiceClass_dep RouteServiceClass_dep RouteServiceClass_dep)
SET(DeferredScribeMSService_sv_list  ScribeMS)
SET(ScribeMSService_sv_list  auto auto auto)
SET(ScribeMSService_dep ${ServiceClass_h} ${TreeServiceClass_dep} ${ScribeTreeServiceClass_dep} ${OverlayRouterServiceClass_dep} ${RouteServiceClass_dep} ${RouteServiceClass_dep})
SET(ScribeService_lib ScribeMS)
SET(DeferredScribeMSService_lib ScribeMS)
SET(DeferredScribeMSService_sv_dep DeferredScribeMS ${ScribeMSService_sv_dep})
