#Mace Configuration File
SET(Mace_SOURCE_DIR "/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext")
SET(Mace_BINARY_DIR "/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds")
SET(DB_CXX_INC_PATH "DB_CXX_INC_PATH-NOTFOUND")
ADD_DEFINITIONS(-DNO_DB_CXX;-D__STDC_FORMAT_MACROS;-D_FILE_OFFSET_BITS=64)

# lib Links and Variables
LINK_DIRECTORIES(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/lib)

# Service Includes and Links
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Transport/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RequestTransport/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Http/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/File/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RandTree/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ReplayTree/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RanSub/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Pastry/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Bamboo/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Chord/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GenericOverlayRoute/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GenericTreeMulticast/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ScribeMS/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SignedMulticast/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SimApplication/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SplitStreamMS/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/FileSync/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/DHT/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/CondorHeartBeat/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/LUFactorization/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/LUFAck/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ThroughputTest/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GameOfLife/mh.cmake)
INCLUDE(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Simple/mh.cmake)
INCLUDE_DIRECTORIES(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/interfaces;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/Transport;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/RequestTransport;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/Http;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/File;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/RandTree;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/ReplayTree;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/RanSub;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/Pastry;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/Bamboo;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/Chord;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/GenericOverlayRoute;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/GenericTreeMulticast;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/ScribeMS;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/SignedMulticast;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/SimApplication;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/SplitStreamMS;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/FileSync;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/DHT;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/CondorHeartBeat;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/LUFactorization;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/LUFAck;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/ThroughputTest;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/GameOfLife;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/services/Simple /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Transport;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RequestTransport;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Http;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/File;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RandTree;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ReplayTree;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RanSub;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Pastry;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Bamboo;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Chord;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GenericOverlayRoute;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GenericTreeMulticast;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ScribeMS;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SignedMulticast;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SimApplication;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SplitStreamMS;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/FileSync;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/DHT;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/CondorHeartBeat;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/LUFactorization;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/LUFAck;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ThroughputTest;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GameOfLife;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Simple)
LINK_DIRECTORIES(/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/interfaces;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Transport;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RequestTransport;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Http;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/File;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RandTree;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ReplayTree;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RanSub;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Pastry;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Bamboo;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Chord;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GenericOverlayRoute;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GenericTreeMulticast;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ScribeMS;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SignedMulticast;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SimApplication;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/SplitStreamMS;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/FileSync;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/DHT;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/CondorHeartBeat;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/LUFactorization;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/LUFAck;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/ThroughputTest;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/GameOfLife;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/Simple)

#Top level properties
INCLUDE_DIRECTORIES(SYSTEM /usr/include/boost-1_42;/usr/include;/homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds)
LINK_DIRECTORIES(/usr/lib)

#Library dependency information
# Generated by CMake 2.8.4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  SET("Bamboo_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("Chord_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("CondorHeartBeat_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("DHT_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("FileSync_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("File_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("GameOfLife_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("GenericOverlayRoute_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("GenericTreeMulticast_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("Http_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("LUFAck_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("LUFactorization_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("MaceMC_LIB_DEPENDS" "general;Transport;general;RequestTransport;general;File;general;RandTree;general;ReplayTree;general;RanSub;general;Pastry;general;Bamboo;general;Chord;general;GenericOverlayRoute;general;GenericTreeMulticast;general;ScribeMS;general;SignedMulticast;general;SimApplication;general;SplitStreamMS;general;FileSync;general;DHT;general;CondorHeartBeat;general;LUFactorization;general;LUFAck;general;ThroughputTest;general;GameOfLife;general;Simple;general;SimulatorCommonFiles;general;interfaces;general;mace;general;m;general;stdc++;")
  SET("Pastry_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("RanSub_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("RandTree_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("ReplayTree_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("RequestTransport_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("ScribeMS_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("SignedMulticast_LIB_DEPENDS" "general;mace;general;GenericTreeMulticast;general;interfaces;")
  SET("SimApplication_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("Simple_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("SimulatorCommonFiles_LIB_DEPENDS" "general;interfaces;general;mace;")
  SET("SimulatorFiles_LIB_DEPENDS" "general;Transport;general;RequestTransport;general;File;general;RandTree;general;ReplayTree;general;RanSub;general;Pastry;general;Bamboo;general;Chord;general;GenericOverlayRoute;general;GenericTreeMulticast;general;ScribeMS;general;SignedMulticast;general;SimApplication;general;SplitStreamMS;general;FileSync;general;DHT;general;CondorHeartBeat;general;LUFactorization;general;LUFAck;general;ThroughputTest;general;GameOfLife;general;Simple;general;SimulatorCommonFiles;general;interfaces;general;mace;general;m;general;stdc++;")
  SET("SplitStreamMS_LIB_DEPENDS" "general;mace;general;ScribeMS;general;GenericTreeMulticast;general;interfaces;")
  SET("ThroughputTest_LIB_DEPENDS" "general;mace;general;Transport;general;interfaces;")
  SET("Transport_LIB_DEPENDS" "general;mace;general;interfaces;")
  SET("adht_LIB_DEPENDS" "general;Http;general;DHT;general;Pastry;general;Transport;general;Http;general;interfaces;general;mace;general;m;general;stdc++;")
  SET("appcommon_LIB_DEPENDS" "general;interfaces;general;mace;")
  SET("interfaces_LIB_DEPENDS" "general;mace;")
  SET("mace_LIB_DEPENDS" "general;/usr/lib64/libpthread.so;general;/usr/lib64/libcrypto.so;general;/usr/lib64/libssl.so;general;/usr/lib64/libcrypto.so;general;/usr/lib64/libgsl.so;general;/usr/lib64/libgslcblas.so;general;/usr/lib64/libz.so;general;/usr/lib64/libgslcblas.so;general;/usr/lib64/libdl.so;general;/usr/lib64/libgslcblas.so;")
  SET("notify_LIB_DEPENDS" "general;Http;general;GenericTreeMulticast;general;Transport;general;RandTree;general;Http;general;interfaces;general;mace;general;m;general;stdc++;")
ELSE("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.4 and lower.
  SET("Bamboo_LIB_DEPENDS" "mace;interfaces;")
  SET("Chord_LIB_DEPENDS" "mace;interfaces;")
  SET("CondorHeartBeat_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("DHT_LIB_DEPENDS" "mace;interfaces;")
  SET("FileSync_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("File_LIB_DEPENDS" "mace;interfaces;")
  SET("GameOfLife_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("GenericOverlayRoute_LIB_DEPENDS" "mace;interfaces;")
  SET("GenericTreeMulticast_LIB_DEPENDS" "mace;interfaces;")
  SET("Http_LIB_DEPENDS" "mace;interfaces;")
  SET("LUFAck_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("LUFactorization_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("MaceMC_LIB_DEPENDS" "Transport;RequestTransport;File;RandTree;ReplayTree;RanSub;Pastry;Bamboo;Chord;GenericOverlayRoute;GenericTreeMulticast;ScribeMS;SignedMulticast;SimApplication;SplitStreamMS;FileSync;DHT;CondorHeartBeat;LUFactorization;LUFAck;ThroughputTest;GameOfLife;Simple;SimulatorCommonFiles;interfaces;mace;m;stdc++;")
  SET("Pastry_LIB_DEPENDS" "mace;interfaces;")
  SET("RanSub_LIB_DEPENDS" "mace;interfaces;")
  SET("RandTree_LIB_DEPENDS" "mace;interfaces;")
  SET("ReplayTree_LIB_DEPENDS" "mace;interfaces;")
  SET("RequestTransport_LIB_DEPENDS" "mace;interfaces;")
  SET("ScribeMS_LIB_DEPENDS" "mace;interfaces;")
  SET("SignedMulticast_LIB_DEPENDS" "mace;GenericTreeMulticast;interfaces;")
  SET("SimApplication_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("Simple_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("SimulatorCommonFiles_LIB_DEPENDS" "interfaces;mace;")
  SET("SimulatorFiles_LIB_DEPENDS" "Transport;RequestTransport;File;RandTree;ReplayTree;RanSub;Pastry;Bamboo;Chord;GenericOverlayRoute;GenericTreeMulticast;ScribeMS;SignedMulticast;SimApplication;SplitStreamMS;FileSync;DHT;CondorHeartBeat;LUFactorization;LUFAck;ThroughputTest;GameOfLife;Simple;SimulatorCommonFiles;interfaces;mace;m;stdc++;")
  SET("SplitStreamMS_LIB_DEPENDS" "mace;ScribeMS;GenericTreeMulticast;interfaces;")
  SET("ThroughputTest_LIB_DEPENDS" "mace;Transport;interfaces;")
  SET("Transport_LIB_DEPENDS" "mace;interfaces;")
  SET("adht_LIB_DEPENDS" "Http;DHT;Pastry;Transport;Http;interfaces;mace;m;stdc++;")
  SET("appcommon_LIB_DEPENDS" "interfaces;mace;")
  SET("interfaces_LIB_DEPENDS" "mace;")
  SET("mace_LIB_DEPENDS" "/usr/lib64/libpthread.so;/usr/lib64/libcrypto.so;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;/usr/lib64/libgsl.so;/usr/lib64/libgslcblas.so;/usr/lib64/libz.so;/usr/lib64/libgslcblas.so;/usr/lib64/libdl.so;/usr/lib64/libgslcblas.so;")
  SET("notify_LIB_DEPENDS" "Http;GenericTreeMulticast;Transport;RandTree;Http;interfaces;mace;m;stdc++;")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
