SET(ALL_SERVICES ${ALL_SERVICES} RanSub)
SET(ALL_SERVICES ${ALL_SERVICES} RanSub2Aggregator)
SET(ALL_SERVICES ${ALL_SERVICES} ransub_test)
SET(ALL_SERVICES ${ALL_SERVICES} RanSubAggregator)
SET(MaceKeyChannelPair_h /homes/bsang/My_Disk/Research/Topic/Full-Context/Mace/mace-fullcontext/builds/services/RanSub/MaceKeyChannelPair.h)
SET(RanSub2AggregatorService_sv_dep RanSub2Aggregator ${autoService_sv_dep} ${autoService_sv_dep})
SET(RanSub2AggregatorService_sv_list  auto auto)
SET(ransub_testService_lib RanSub)
SET(RanSubService_lib RanSub)
SET(RanSubService_sv_dep RanSub ${autoService_sv_dep})
SET(RanSubAggregatorService_lib RanSub)
SET(ransub_testService_tgt_dep ServiceClass_dep NullServiceClass_dep GossipServiceClass_dep)
SET(RanSub2AggregatorService_tgt_dep ServiceClass_dep AggregateServiceClass_dep TreeServiceClass_dep TransportServiceClass_dep)
SET(RanSubService_tgt_dep ServiceClass_dep GossipServiceClass_dep AggregateServiceClass_dep)
SET(RanSubAggregatorService_tgt_dep ServiceClass_dep AggregateServiceClass_dep TreeServiceClass_dep TransportServiceClass_dep)
SET(RanSubService_sv_list  auto)
SET(RanSubAggregatorService_dep ${ServiceClass_h} ${AggregateServiceClass_dep} ${TreeServiceClass_dep} ${TransportServiceClass_dep})
SET(ransub_testService_sv_dep ransub_test ${autoService_sv_dep})
SET(RanSub2AggregatorService_dep ${ServiceClass_h} ${AggregateServiceClass_dep} ${TreeServiceClass_dep} ${TransportServiceClass_dep})
SET(RanSub2AggregatorService_lib RanSub)
SET(RanSubAggregatorService_sv_list  auto auto)
SET(RanSubAggregatorService_sv_dep RanSubAggregator ${autoService_sv_dep} ${autoService_sv_dep})
SET(ransub_testService_dep ${ServiceClass_h} ${NullServiceClass_dep} ${GossipServiceClass_dep})
SET(RanSubService_dep ${ServiceClass_h} ${GossipServiceClass_dep} ${AggregateServiceClass_dep})
SET(ransub_testService_sv_list  auto)
SET(MaceKeyChannelPair_dep ${MaceKeyChannelPair_h})
